root: true
plugins:
  - import
  - jest
  - react
  - ssr-friendly
extends:
  - eslint:recommended
  - plugin:import/recommended
  - plugin:react/recommended
  - plugin:ssr-friendly/recommended
parserOptions:
  ecmaVersion: 2021
  ecmaFeatures:
    jsx: true
  sourceType: module
settings:
  react:
    version: "17"
env:
  browser: true
  es6: true
  node: true
rules:
  import/no-named-as-default: off
  import/order:
    - error
    - alphabetize:
        order: asc
        caseInsensitive: true
      newlines-between: always
  react/prop-types: off
  react/self-closing-comp: error
overrides:
  - files: "*.test.js"
    extends:
      - plugin:jest/recommended
