root: true
plugins:
  - import
  - react
extends:
  - eslint:recommended
  - plugin:import/recommended
  - plugin:react/recommended
parser: babel-eslint
parserOptions:
  ecmaFeatures:
    jsx: true
env:
  browser: true
  es6: true
  node: true
rules:
  import/no-named-as-default: off
  import/order:
    - error
    - alphabetize:
        order: asc
        caseInsensitive: true
      newlines-between: always
  react/prop-types: off
  react/self-closing-comp: error
